server:
  port: 8090
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: stomp
          uri: ws://localhost:8091
          predicates:
            - Path=/notifications
        - id: radio
          uri: http://localhost:8092
          predicates:
            - Path=/radio/**
          filters:
            - StripPrefix=1
logging:
  level:
    root: info
    at.wrk.coceso: debug
