# This profile uses the docker-compose DNS names and is activated for the default docker-compose build

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: stomp
          uri: ws://coceso-stomp:8080
          predicates:
            - Path=/notifications
        - id: radio
          uri: http://coceso-radio:8080
          predicates:
            - Path=/radio/**
          filters:
            - StripPrefix=1
logging:
  config: /config/log-docker.xml
  level:
    root: info
    at.wrk.coceso: debug
