# This profile uses the docker-compose DNS names and is activated for the default docker-compose build

spring:
  rabbitmq:
    host: coceso-amqp
    username: coceso-rabbitmq-user
    password: coceso-rabbitmq-pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./database/coceso-radio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: coceso-radio
    password: coceso-radio
  h2:
    console:
      enabled: true
logging:
  config: /config/log-docker.xml
  level:
    root: info
    at.wrk.coceso: debug
