server:
  port: 8091
application:
  services:
    radio: http://localhost:8092
  broker:
    host: localhost
    username: coceso-rabbitmq-user
    password: coceso-rabbitmq-pass
logging:
  level:
    root: info
    at.wrk.coceso: debug
