server:
  port: 8091
application:
  broker:
    host: localhost
    username: coceso-rabbitmq-user
    password: coceso-rabbitmq-pass
spring:
  rabbitmq:
    host: localhost
    username: coceso-rabbitmq-user
    password: coceso-rabbitmq-pass
logging:
  level:
    root: info
    at.wrk.coceso: debug
