server:
  port: 8093
spring:
  rabbitmq:
    host: localhost
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
  datasource:
    url: jdbc:postgresql://localhost:5432/mls-coceso?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: mls-coceso
    password: mls-coceso-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non_contextual_creation: true
          time_zone: UTC

application:
  auth:
    verification:
      signing-key: classpath:dev.pub

logging:
  pattern:
    console: "%d %highlight(%-5level) [%12.12thread] %cyan(%logger{5}): %msg%n"
  level:
    at.wrk.fmd.coceso: debug
