server:
  port: 8093
spring:
  rabbitmq:
    host: localhost
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
  datasource:
    url: jdbc:postgresql://localhost:5432/mls-coceso?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: mls-coceso
    password: mls-coceso-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  auth:
    verification:
      signing-key: classpath:dev.pub
  messages:
    templates:
      alarm: |
        CCS{{incidentId}}: {{type}}
        BO: {{bo}}
        {{info}}
        Einheiten: {{units}}
        BO URL: {{boUrl}}
      casus: |
        CCS{{incidentId}}
        AO: {{ao}}
        Casus: {{casusNr}} {{erType}}
        AO URL: {{aoUrl}}
    channels:
      - id: /dev/ttyUSB50
        name: Test Port 1
      - id: /dev/ttyUSB51
        name: Test Port 2

logging:
  pattern:
    console: "%d %highlight(%-5level) [%12.12thread] %cyan(%logger{5}): %msg%n"
  level:
    at.wrk: debug
